### ISSUE TITLE
Where is the up to date API documentation hosted?

### ISSUE THREAD

**Issue by gajus** [chaijs/chai-docs#129]
I thought that this syntax has been deprecated many years ago:

http://chaijs.com/api/bdd/#method_true

```js
expect(true).to.be.true;
expect(1).to.not.be.true
```

in favor of:

```js
expect(true).to.equal(true);
expect(1).to.not.equal(true);
```

But I cannot either see a notice about this in the documentation or an up-to-date documentation.

**Comment by keithamus** [comment]
@gajus thanks for the issue.

As far as I know the syntax was never deprecated. You are free to use whichever one you want.

As for this documentation - it is up to date with the latest released version of Chai, and built at least once every 24 hours, if not more.

I'll close this issue because of the above, but feel free to discuss things further, or raise any new issues as you find them 😄

**Comment by gajus** [comment]
Interesting. I remember getting errors when using this syntax in the past, advising to use the explicit method invocation syntax. Of course, there is a slight change that my memory has been invaded by day dreams.

**Comment by keithamus** [comment]
There's been lots of back and forth about this - the latest of which is here: https://github.com/chaijs/chai/issues/690. Hopefully that provides you with the right information about what is what with regards to property assertions.

**Comment by gajus** [comment]
Thank you @keithamus. This makes a lot more sense. Forgot about dirty-chai.
