### ISSUE TITLE
assert.notInclude code is not properly formatted

### ISSUE THREAD

**Issue by platinumazure** [chaijs/chai-docs#93]
See http://chaijs.com/api/assert/#-notinclude-haystack-needle-message-.

**Comment by keithamus** [comment]
Thanks for the issue @platinumazure!

This has been fixed within the documentation via #458. Unfortunately we have yet to update the website because it's a very manual process right now, and the aim is to make it more automated - but that is taking a little while. See chaijs/chai-docs#74 for more.

I'll close this, because it will be fixed as soon as chaijs/chai-docs#74 is done.
